enterpriseServer:
  url: http://10.10.100.151:8080
  apiKey: lmvg37G8U25yxKSQRhsRwVw5Q9EbZUDl
  # Add the TLS certificate if needed

site:
  correlationId: CommandInjectionAppScan
  startUrls: 
    - http://localhost:3000/

scanConfigurations:
  builtIn: 
    - Crawl and Audit - CICD optimized

logins:
  # If your app requires authentication, set up the login credentials or recorded sequences. If it doesn't, you can ignore this part.

reporting:
  reportFormats:
    - JUNIT
  threshold:    
    minimumSeverity: LOW
    minimumConfidence: TENTATIVE
    enabled: true
