enterpriseServer:
  url: http://10.10.100.151:8080
  apiKey: lmvg37G8U25yxKSQRhsRwVw5Q9EbZUDl
  # Add the TLS certificate if needed

site:
  correlationId: CommandInjectionAppScan
  startUrls: 
    - http://10.10.100.151:3000/

scanConfigurations:
  builtIn: 
    - Crawl and Audit - CICD optimized

reporting:
  reportFormats:
    - JUNIT
  threshold:    
    minimumSeverity: LOW
    minimumConfidence: TENTATIVE
    enabled: true
